const state={loaded:false,meta:null,ranges:{},indices:{},mode:'pan',zoom:{axial:1,sagittal:1,coronal:1},pan:{axial:[0,0],sagittal:[0,0],coronal:[0,0]},wl:{width:400,level:40},painting:false,measureStart:null};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function notify(text,error=false){const e=$('#message');e.textContent=text;e.classList.toggle('error',error)}
async function request(url,opts={}){try{const r=await fetch(url,opts);const ct=r.headers.get('content-type')||'';if(!r.ok){let d=ct.includes('json')?await r.json():{detail:await r.text()};throw Error(d.detail||'Request failed')}return ct.includes('json')?await r.json():r}catch(e){notify(e.message,true);throw e}}
function applyStatus(d){state.loaded=d.loaded;state.meta=d.metadata;state.ranges=d.ranges||{};['infer','clear','export'].forEach(id=>$('#'+id).disabled=!d.loaded);updateHistory(d.history);if(d.loaded){for(const p of ['axial','sagittal','coronal']){const s=$(`[data-plane=${p}] .slice`);s.max=d.ranges[p]-1;if(!Number.isFinite(state.indices[p])||state.indices[p]<0||state.indices[p]>=d.ranges[p])state.indices[p]=Math.floor(d.ranges[p]/2);s.value=state.indices[p]}renderStudy();updateMetrics(d.mask);$('#provenance').textContent=d.provenance.provider||d.provenance.type;renderAll();notify(`Loaded ${d.metadata.source_name} · ${d.metadata.shape.join(' × ')} voxels`)}$('#system').textContent=d.native_core?'● C++ CORE ONLINE':'● PYTHON FALLBACK'}
function updateHistory(h={}){$('#undo').disabled=!h.can_undo;$('#redo').disabled=!h.can_redo}
function renderStudy(){const m=state.meta;$('#study').innerHTML=`<h2>STUDY DETAILS</h2><div class="study-grid"><span>Source</span><span>${m.source_type}</span><span>Name</span><span>${m.source_name}</span><span>Modality</span><span>${m.modality}</span><span>Matrix</span><span>${m.shape.join(' × ')}</span><span>Spacing</span><span>${m.spacing_mm.map(x=>x.toFixed(2)).join(' × ')} mm</span><span>Patient</span><span>${m.patient_id}</span></div>`}
function updateMetrics(m){if(!m)return;$('#voxels').textContent=m.voxel_count.toLocaleString();$('#volume').textContent=m.volume_mm3.toLocaleString()+' mm³';$('#backend').textContent=m.backend}
function renderAll(){if(!state.loaded)return;for(const p of ['axial','sagittal','coronal'])render(p)}
function render(p){const f=$(`[data-plane=${p}]`),img=f.querySelector('img');img.src=`/api/slice/${p}/${state.indices[p]}?level=${state.wl.level}&width=${state.wl.width}&t=${Date.now()}`;img.style.transform=`translate(${state.pan[p][0]}px,${state.pan[p][1]}px) scale(${state.zoom[p]})`;f.querySelector('.coord').textContent=`${state.indices[p]+1} / ${state.ranges[p]}`}
async function loadFiles(files,type){if(!files.length)return;notify('Loading and validating image data…');const fd=new FormData;if(type==='nifti')fd.append('file',files[0]);else for(const f of files)fd.append('files',f);const d=await request(type==='nifti'?'/api/load-nifti':'/api/load-dicom',{method:'POST',body:fd});applyStatus(d)}
$('#demo').onclick=async()=>applyStatus(await request('/api/load-demo',{method:'POST'}));$('#nifti').onchange=e=>loadFiles(e.target.files,'nifti');$('#dicom').onchange=e=>loadFiles(e.target.files,'dicom');
$('#infer').onclick=async()=>{notify('Running deterministic demo segmentation…');const d=await request('/api/infer',{method:'POST'});applyStatus(d);notify(`Segmentation complete · ${d.provider} (non-clinical demo)`) };
$('#clear').onclick=async()=>applyStatus(await request('/api/clear-mask',{method:'POST'}));$('#export').onclick=()=>{location.href='/api/export';notify('Export prepared: NIfTI mask + JSON metadata')};
async function historyAction(action){const d=await request('/api/'+action,{method:'POST'});applyStatus(d);notify(action==='undo'?'Last mask change undone':'Mask change restored')}
$('#undo').onclick=()=>historyAction('undo');$('#redo').onclick=()=>historyAction('redo');
for(const el of $$('.slice'))el.oninput=e=>{const p=e.target.closest('figure').dataset.plane;state.indices[p]=+e.target.value;render(p)};
for(const b of $$('[data-wl]'))b.onclick=()=>{[state.wl.width,state.wl.level]=b.dataset.wl.split(',').map(Number);$('#window').value=state.wl.width;$('#level').value=state.wl.level;$('#windowOut').textContent=state.wl.width;$('#levelOut').textContent=state.wl.level;renderAll()};
for(const id of ['window','level'])$('#'+id).oninput=e=>{state.wl[id]=+e.target.value;$('#'+id+'Out').textContent=e.target.value;renderAll()};
for(const b of $$('[data-mode]'))b.onclick=()=>{state.mode=b.dataset.mode;$$('[data-mode]').forEach(x=>x.classList.toggle('active',x===b));$$('canvas').forEach(c=>c.style.cursor=state.mode==='pan'?'grab':'crosshair')};
$('#brush').oninput=e=>$('#brushOut').textContent=e.target.value;
for(const f of $$('figure')){const p=f.dataset.plane, canvas=f.querySelector('canvas');let last=null;
 canvas.onwheel=e=>{e.preventDefault();if(e.ctrlKey||e.metaKey){state.zoom[p]=Math.max(.5,Math.min(5,state.zoom[p]*(e.deltaY>0?.9:1.1)))}else{state.indices[p]=Math.max(0,Math.min(state.ranges[p]-1,state.indices[p]+(e.deltaY>0?1:-1)));f.querySelector('.slice').value=state.indices[p]}render(p)};
 canvas.onpointerdown=e=>{canvas.setPointerCapture(e.pointerId);last=[e.clientX,e.clientY];state.painting=true;if(state.mode==='measure')state.measureStart=last;if(['paint','erase'].includes(state.mode))paint(e,p,canvas)};
 canvas.onpointermove=e=>{if(!state.painting)return;if(state.mode==='pan'){state.pan[p][0]+=e.clientX-last[0];state.pan[p][1]+=e.clientY-last[1];last=[e.clientX,e.clientY];render(p)}else if(['paint','erase'].includes(state.mode))paint(e,p,canvas);else if(state.mode==='measure')drawRuler(canvas,state.measureStart,[e.clientX,e.clientY],p)};
 canvas.onpointerup=e=>{state.painting=false;if(state.mode==='measure')drawRuler(canvas,state.measureStart,[e.clientX,e.clientY],p,true)};
}
async function paint(e,p,c){const r=c.getBoundingClientRect();const d=await request('/api/paint',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({plane:p,index:state.indices[p],u:(e.clientX-r.left)/r.width,v:(e.clientY-r.top)/r.height,radius:+$('#brush').value,value:state.mode==='paint'?1:0})});updateMetrics(d.mask);updateHistory(d.history);render(p)}
function drawRuler(c,a,b,p,final=false){const r=c.getBoundingClientRect(),ctx=c.getContext('2d'),x1=a[0]-r.left,y1=a[1]-r.top,x2=b[0]-r.left,y2=b[1]-r.top;c.width=r.width*devicePixelRatio;c.height=r.height*devicePixelRatio;ctx.scale(devicePixelRatio,devicePixelRatio);ctx.strokeStyle='#ffd15c';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(x1,y1);ctx.lineTo(x2,y2);ctx.stroke();const spacing=p==='axial'?state.meta.spacing_mm.slice(0,2):p==='sagittal'?[state.meta.spacing_mm[1],state.meta.spacing_mm[2]]:[state.meta.spacing_mm[0],state.meta.spacing_mm[2]];const mm=Math.hypot((x2-x1)*spacing[0]/r.width*state.meta.shape[0],(y2-y1)*spacing[1]/r.height*state.meta.shape[1]);$('#measurement').textContent=`${mm.toFixed(1)} mm · ${p} plane${final?' (saved until next measurement)':''}`}
const drop=$('#drop');drop.ondragover=e=>{e.preventDefault();drop.style.borderColor='#13ceaa'};drop.ondragleave=()=>drop.style.borderColor='';drop.ondrop=e=>{e.preventDefault();drop.style.borderColor='';loadFiles(e.dataTransfer.files,'nifti')};
request('/api/status').then(applyStatus);
document.addEventListener('keydown',e=>{if(!(e.ctrlKey||e.metaKey)||e.key.toLowerCase()!=='z')return;e.preventDefault();if(e.shiftKey){if(!$('#redo').disabled)historyAction('redo')}else if(!$('#undo').disabled)historyAction('undo')});
